spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fxy_financial?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    password: fxy_financial
    username: fxy_financial
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    "cn.gson.financial.kernel.model.mapper": info
  path: /data/worker/logs

mybatis-plus:
  type-aliases-package: cn.gson.financial.kernel.model.entity
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mappers/*Mapper.xml