spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fxy?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    password: 12qwaszx
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    # Redis数据库索引（默认为0）
    database: 10
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

logging:
  level:
    "cn.gson.financial.kernel.model.mapper": debug


mybatis-plus:
  type-aliases-package: cn.gson.financial.kernel.model.entity
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mappers/*Mapper.xml

aliyun:
  accessKeyId:
  accessKeySecret:
  sms:
    signature: 纷析云
    template-code:
      verification: SMS_175580136
      register: SMS_183262497

sa-token:
  token-session-check-login: false
  is-share: false
  is-concurrent: true
  token-name: fsatoken
